### ISSUE TITLE
Kick message outputting twice & without an executor replacement.

### ISSUE THREAD

**Issue by mibby** [ruany/LiteBans#31]
LiteBans v2.2.4

Testing kick messages. Noticed the kick message is outputting twice.

With BungeeCord set false.
![link](https://i.imgur.com/IPGEDon.png)

With BungeeCord set true.
![link2](https://i.imgur.com/epsRmFu.png)

```
  kick:
    usage: '&f/kick <player> [reason]'
    no_match: '&fError: &6Player not found.'
    message: 'Kicked by $executor: $reason'
    message_no_reason: Kicked by $executor.
    response: '&6$player &fhas been kicked by &6$executor'
    broadcast: '&6$player &fhas been kicked by &6$executor'
    broadcast_no_reason: '&6$player &fhas been kicked by &6$executor'
    exempt: '&fYou can''t kick $player!'
    kick_requested: '&6Player $player is not online on this server. Cross-server kick
      has been requested.'
```
